name: Auto Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: '40 6 * * 1-5'  # 12:10 PM IST, Monday to Friday

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run Selenium script
      run: python Test1.py

    - name: Upload debug artifacts (if any)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: selenium-debug
        path: |
          debug_screenshot.png
          page_source_debug.html
